I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 55, in script
    with dissolve(.5)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 55, in script
    with dissolve(.5)
  File "C:\Users\wbm007\Desktop\renpy-7.3.2-sdk\renpy\ast.py", line 1387, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\wbm007\Desktop\renpy-7.3.2-sdk\renpy\exports.py", line 1592, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\wbm007\Desktop\renpy-7.3.2-sdk\renpy\display\core.py", line 2248, in do_with
    clear=clear)
  File "C:\Users\wbm007\Desktop\renpy-7.3.2-sdk\renpy\display\core.py", line 2699, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\wbm007\Desktop\renpy-7.3.2-sdk\renpy\display\core.py", line 3044, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Windows-8-6.2.9200
Ren'Py 7.3.2.320
Doki Doki FSM 1.0
Mon Sep 23 15:13:06 2019
