I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 35, in script
    e "The longer you leave me the more powerful i will become"
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 35, in script
    e "The longer you leave me the more powerful i will become"
  File "C:\Users\wbm007\Desktop\renpy-7.3.2-sdk\renpy\ast.py", line 676, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\wbm007\Desktop\renpy-7.3.2-sdk\renpy\ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'e' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.2.320
Doki Doki FSM 1.0
Mon Sep 23 13:09:37 2019
